<script>
import { ref } from 'vue';
import VideoEmbed from '../../components/VideoEmbed.vue';

export default {
    components: {
        VideoEmbed,
    },
};
</script>

<template>
    <div class="container mx-auto py-4 px-3 flex flex-col grow md:overflow-scroll md:overflow-y-hidden">
        <div class="columns-md gap-8 md:max-h-[calc(100vh_-_200px)]">
            
            <div class="flex justify-between mb-6">
                <div class="text-xl mb-3 font-roboto font-extrabold uppercase">
                    Amanda Beech<br />
                    Ellis von Sternberg<br />
                    In Conversation
                </div>
                <a
                    href="/docs/delphic-future/beech-evs-interview.pdf"
                    target="_blank"
                    >PDF</a
                >
            </div>
            <div>
                <div class="pb-6 break-inside-avoid">
                    <img src="/images/delphic-future/install-1.jpg" class="max-w-full md:max-h-[calc(100vh_-_300px)] h-auto w-auto" />
                    <p class="text-sm">Amanda Beech, "Delphic Future", 2024 installation view at Twelve Ten Gallery.</p>
                </div>
                <p class="mb-3">
                    <strong>Ellis von Sternberg</strong> I would like to open this up with a question regarding artistic practice: your work is embedded in a rigorous study of art's enlightenment philosophical forebears and the subsequent continental critics of that philosophical project in the 20th century. As I understand it, the practical category of a given research, in its scientific tradition, is inherently specific to the areas of study the method of that research pertains to. This is to say that the specialized rules defining a given method constrain research, at the level of practice, to the specialized area that it studies. If research, then, has rules and norms it must adhere to in order to minimally qualify as relevant in its field, do you believe artistic research is also rule bound? If so, would it be accurate to say art and art practices are the ends of an artist's given research method rather than an end unto themselves? How then do your philosophical studies come to inform the way you work as an artist? Is it part of the art itself or does it preempt, and possibly preclude, the work?

                </p>
                <p>
                    <strong>Amanda Beech</strong> That's a big opening question, but this is great because it's something that I’ve been grappling with a long time. I think that the first part of the question highlights how a discipline that claims any kind of scientificity  becomes self-aware of its own bias or subjectivism. For some, that spelled the end of the possibility of a science, because it says that everything becomes subjective. There was no hope anymore for objectivity, everything is contextual, everything is contingent, everything is psychological or perspectival. This kind of hand-wringing response is something that I see to have been over-determined, for it misses out on the objective conditions that are also at play within any situation. The idea that everything is subjective holds the fallacy of open possibilities. But as we know full well, in the context of capitalism the myth of openness and plurality is  very much the core to its  ideological framework.  We find that the legacy of critique has actually brought us to a form of subjective idealism that is really reflective of the core principles of capitalist ideology itself. This is plainly unsatisfactory. So what I'm really interested in is how we can think through a productive self consciousness rather than this  debilitating form.</p>
                <p>
                    I think that it is also important to note that when practices become aware of their imbrication within their own methods they actually calcify or concretize themselves as a discrete  discipline, forming their own worlds through this recursive self reference to their own autonomy. Without the very idea of self consciousness, an operation that is deeply connected to art's  history as a bourgeois concept, disciplines don't become aware of their own problems and construction. In terms of the avant-garde as we know it, art spent a lot of time attempting to negate this autonomy, which only reinforced it all the more. Today, we still see this as a move, when artists are saying they are no longer just doing art, they are doing maths, or social sciences, or anthropology, or community care. Because of this persistent bind the task of art to become political has been performed in the attempt to disaggregate the classification that actually gives it its authority. Because it is hard to tell the difference between the disavowal of a form of power that classifies difference according to economic conditions of capitalism and the disavowal that autonomy grants in itself we find art in a deeper crisis, one which it bemoans its imprisonment or it claims to ironically enjoy. The point regarding rules is that art's self consciousness acts as if there are rules and hierarchies that it has no access to and this generates these fatalistic conditions in socio-political and material terms.
                </p>
                <p>
                    So obviously I believe the rules of art are constructed through this bourgeois apparatus in capitalism, but despite the fact that we might not like where those rules come from, in its class based economic conditions, as a discipline that can think, and thus act and make and produce images unto itself, I think that these specific rules that we work with that can take art past, or hopefully exceed the constraints from those "origins".
                </p>
                <p>
                    One of the affiliations we can see, from this perspective, between art and philosophy, is that they both have the capacity to engage the premises on which their own reasons are constructed. And in this there is the capacity to engage in the idea that there are no premises for reason itself, where we deal with a sense of groundlessness in practice. Where we begin a practice from is always a very interesting question when one accepts that there are no premises. When there are no premises, what one is allowed to play with is rules, we are allowed to build systems and procedures. It is a labor of thought between all art and I think that it is also a labor shared with philosophy. Art is able to do the specific conceptual labor that is common to all types of philosophy, which allows it to address the question you asked: the question of art's imbrication in the very situation in which we are thinking art as such.
                </p>
                <div class="mb-6 break-inside-avoid">
                    <img src="/images/delphic-future/patterns-nature-install-1.jpg" class="max-w-full md:max-h-[calc(100vh_-_300px)] h-auto w-auto" />
                    <p class="text-sm">Amanda Beech, "Delphic Future", 2024 installation view at Twelve Ten Gallery.</p>
                </div>
                <p>
                    <strong>EVS</strong> It denotes an urgency for us to outthink art’s saturation with its own history, and  the way in which art’s historical awareness has been developed into a critically idealized concept. This actually brings a rigor to our study of art: one has to be constantly aware of how that historical awareness has happened, and in that, find a type of unique, and rather caustic potential. Otherwise, there is no way to distinguish something like a generalized cultural technique from art in our practices, which is precisely the return to that subjective idealization you mentioned.  An individual practice has a history, it has an institution and publication and documentation at the material level, and admitting that brings pressures on to the way in which a practice develops: we need to admit how some practices appropriate that which they study. What I understand you to be saying, is that the study of art is also the study of philosophy, as any truly critical study itself has philosophical pretenses. While neither art nor philosophy is collapsible into the other, they must be held to a standard of responsibility with how they inherently affect the world.

                </p>
                <p>
                    <strong>AB</strong> Yes, one of the things about art is that one spends a long time constructing a methodology. Having no repeatable method that can be applied to all forms of practice calls upon the larger idea that there are no premises for reason per se. This is not to say that all art can and should do is splurge out some libidinal noise and that will be sufficient to reflect this lack of premises. To do this would be to render some fantasy of the incomputable, or the rift between what reason is and what it does as kitsch. It is also contradictory, for this appeal to a groundless nature must be cultivated as a genre of aesthetic experience (a pseudo non-representationalist rival to art as "artifice"). This means ultimately that the claim that aesthetic experience can occupy a place in which rules are suspended is impossible. Therefore we must approach the idea that rules must be taken even more seriously in determining what implicit and ideological conditions constrain and potentialize what actually be made and constructed.
                </p>
                <p>
                    <strong>EVS</strong> When we look at the criticisms that emerged out of postmodernism and the tool set that is provided to us via the enlightenment, there is a genealogy we can derive for contemporary art's relationship to modernity, and modernity's relation to the notion of creativity, and then art and its relationship to institutions, and then how all of those things are bound up in the institution's role in imperialism and, finally, how all of this deploys the concept of property at its core. This is a conventional critical narrative, which I don't disagree with, but look where it has led us within the practice of art: with an inability to direct our own practices, and relying on outside literary or theoretical institutions that use art as a didactic device and nothing more. What you are talking about is, instead, an almost gleeful embrace in the fact that we have been given, from the outset, a tool set from the enlightenment, which has an extremely corrosive potential to dismantle rules, reengineer ideas, and to suss out the areas of thought that may actually dictate how we can act or think. This is only possible when one has a comprehensive understanding of how a system actually operates. When I truly understand how, for example, how a car engine works then I am much better poised to make that engine inoperable. I can intervene in its function much more effectively when I know the mechanics of the engine. Not to discredit the effective nature of blowing up the car as well. That will always work.
                </p>
                <p>
                    <strong>AB</strong> I agree, it is to take seriously the teachings of our enlightenment forebears, as you have phrased it, and to also take as inspiration the criticisms that emerge out of the continental school, but importantly, not to be satisfied with those criticisms as complete or conclusive. Because obviously they didn't entirely succeed.
                </p>
                <p>
                    <strong>EVS</strong> I feel like this is a good lead into my second question, which is a bit more specific to your actual artworks: with regard to your upcoming show and the screening that will take place at the Music Box Theatre, what is important to you about working with neo-noir, hard boiled, pulp, and the US post cold war cold world narratives of conspiracy? When these conventional forms of video and plot are deployed within the art world or gallery setting, what is being demonstrated?
                </p>
                <p>
                    <strong>AB</strong> There's so much to say about the genre of noir in itself. Let's start with what I feel is pretty obvious. Films like  <em>Double Indemnity</em> or <em>The Maltese Falcon</em>,  feature an alienated human or humans who can't connect with each other nor with the world. The way the films are lit is crucial to this sensibility. Harsh directional lights shine into people's faces  making shadows that cut faces and bodies into fragments. The treatment of subjects like objects, shows us a  cold world, a world alienated all the way down. And yet, in these films, it's the people who are alienated the most, who are without family links, lacking a regular job, or being down on their luck that can act, and cut through the cold world, not to find any redemption but to resolve matters of justice and truth. What interests me is how this drive to the question of the universal, is done in the dark; a kind of thinking or epistemology in the dark if you like. I think this rings very true with the lack of inherent premises that we were just discussing, grasping and learning in the dark, constructing as we go. So it also speaks to a kind of strand of american pragmatism, which was also being written at the same time where there was this idea that while we are adrift from the original ideas of the enlightenment and Kantian forms of assertive rationalism we are still constructing worlds. 
                </p>
                <div class="mb-6 break-inside-avoid">
                    <VideoEmbed embedCode="XaswpDf-jMI" />
                    <p class="text-sm"><em>Map of the Bomb</em> premiere trailer.</p>
                </div>
                <p>
                    My most recent work is the most literal manifestation of this idea. <em>Map Of A Bomb</em> (2022) draws a central narrative axis from Dashiell Hammett's short story "The Red Harvest" (1929). "The Red Harvest" has been made into many films, there's Kurasowas’ <em>Yojimbo</em> (1961) and Clint Eastwood in Sergio Leone's <em>A Fistfull of Dollars</em> (1964) and Bruce Willis in Walter Hill’s <em>Last Man Standing</em> (1996) but it has never had its own adaptation for the screen. In that respect the book acts like the auratic condition of noir in contemporary and modern cinema acting as the abiding hollow center for the genre. The basic story for Hammett is that a cop arrives in a town called Poisonville and he's asked to solve a crime that has taken place. But throughout the story every character just ends up dead. In this narrative everything is corrupt, everything down to the dust, Hammett was showing us a world of utter corruption, no outside. I took the strain of this book as the grounds for the action, a site in which a duo, a vampiric immortal woman who knows all and has done it all works with the flat foot pragmatic cop to organize a system that can decrypt the complexity of reality into a new language, as if we can read the heart of reality itself through forms of complex encryptions. The characters that do this are based on real life events, where the famous Hollywood actress Hedy Lamarr and the composer of "Ballet Mecanique", George Anthiel invented Spread Spectrum Frequency Hopping. This invention gave way to wi-fi and cell phone communications technology today, but it started off with experiments on the piano.  I wanted to ask in the work what becomes of transcendence once everything is equally unredeemable? Can there be a way to map the irreducibility of the relations between transcendence and materiality via a system and what is it to navigate this process dynamics?
                </p>
                <p>
                    <strong>EVS</strong> I don't know the theatrical or cinematic term, but the use of characters to parodize or perform the traditional dialectic of western philosophy is made clear throughout the film. I think that's great. I also think it does a great job at working with the other convention of noir, which is conspiracy. Noir is recognizable based on certain tropes, or to relate it to our earlier terms, it has a certain set of rules and norms it adheres to so as to obtain a categorically nameable place as noir, and conspiracy is one of the main conventions we apply to understand that category. I think there's a historically conspiratorial narrative that can be read into the evolution of the bourgeois ideals of the 18th and 19th centuries in the development of the novel. What we see is that, first, literacy is steadily rising, the printing press is emerging as a totally dominant technology, and both events are important for Kant to articulate how he believes students can now come to teach themselves through their ability read and access all sorts of written material, but this is all while the epistolary novel is being developed as a highly available consumer product. But what happens is that it is not the idealized bourgeois subject who is most affected by this technological and conceptual development, which is the constrained intention of Kant's work, but instead the parlor and the women of the home. Where they were able to come to a mass collective awareness, and at the same time a self-awareness, by reading fictional, mass disseminated, testimonial writing of other women's inner lives. This is the initial, progenitorial, roll towards the literary and structural turn that seized all of philosophy by the '60s. The novel, which was intended to be a kind of spectacular commodity, a pulp commodity, inadvertently produces the conditions for certain subjects within a fixed hierarchy to perceive the constructedness of their imposed status, and so the constructedness of the hierarchy. That the construction, or the conspiracy, goes all the way to the top. It's noir. What is taught in noir is that authority is always potentially flawed, and that's the same core teaching of Kant: hierarchy is built, not given. Authority, on its metaphysical level, is dragged down to suspicion.
                </p>
                <p>
                    <strong>AB</strong> Right, noir is always a plot that recognizes the contingent nature of power and these descriptions of alienation are populist. Both philosophy and fiction in this way give better vantage points for us to look into how the given order of affairs are always organized, and concealed, by people and by history. I think this is important when art can unfortunately end up aiding and abetting that current state of affairs, as we have just said, not just by aiming to escape them <em>but in the process of understanding them</em>. There's art that can enjoy this kind of crisis it finds itself in, there's art that can describe crisis, and of course there's art that can just act like there is no crisis. Each naturalizes it. Can art manifest something that is beyond the paranoiac and conspiratorial; its boundness to that which it seeks to change including its own self-image? This begs the question of what the imagination can do and is. What is it to think about imagination as a technical apparatus that we can work through that allows us to generate something that is entirely alien to the thinker themselves but which can take place as a language/system? 
                </p>
                <div class="mb-6 break-inside-avoid">
                    <img src="/images/delphic-future/engaging-1.jpg" class="max-w-full md:max-h-[calc(100vh_-_300px)] h-auto w-auto" />
                    <p class="text-sm">Amanda Beech, <em>Engaging in an Enterprise and Then Mysteriously Disappearing</em>, 2023, Acrylic on Paper, 58.5 in. x 55 in.</p>
                </div>
                <p>
                    <strong>EVS</strong> Since we are talking about this kind of inhumanism, this algorithmic direction that is alien but nonetheless comprehensible to thought, I want to turn to the paintings that will be in the show. In the midst of this baroque imagery, spilling between naturalistic and industrial forms, is a repeated diagram of a geometric or clockwork apparatus: Ramon Llull's <em>Ars</em>, could you explain what this is and where it comes from?
                </p>
                <p>
                    <strong>AB</strong> Of course, when I was making both <em>Covenant Transport Move or Die</em> (2015) and <em>Map of the Bomb</em> (2022)  I was really involved in the history of inventions that attempted a mapping of complexity; technologies that map indifferent systems by offering them in understandable ways, aiming to solicit infinite variations through finite means. What I find  most interesting is the way the techniques mapping these systems have been implanted in natural language as opposed to mathematics or physics (as we have seen in the philosophy and non-philosophy of Badiou and Laurelle). I am interested in the relation between these scientific and philosophical questions and how natural language is necessary as part of these processes, and the politics and force of that language is one of mediation and construction. Ramon Llull, a monk in Palam, Majorca, working around 1260 made a machine that was a series of wheels within wheels, each one capable of moving autonomously and each one holding words with specific values relating to ethics. For Llull this device enabled its player to move through random possibilities to eventually find the truth of a Christian God. The machine that held all this openness had an end in mind, and was used to convert Muslims to Christianity. So as you were mentioning before, when a scientist starts off with a theory there needs to be an awareness of how the theory itself is reliant upon other beliefs. This system was echoed later by Liebniz, but in  the 1920’s we see its manifestation in pop culture. It inspired William Wallace Cook to write <em>Plotto</em>, a manual for the production of fiction. This was used by Alfred Hitcock and appears in George Orwell’s work as well as Jonathan Swift’s <em>Gulliver’s Travels</em>. The idea of an endless fiction, a neverending fiction through a system that claims openness, has continued ramifications. We know that these types of systems eventually became implemented in computational science and algorithmic science today where we experience Amazon predicting our desires everyday. What these systems point to is how attempts to render the open field of possibilities that we conceptualize in nature are not reducible to the thing they refer to, but instead produce a second nature. This is the space of abstraction and ideology, a world rendered by decryption descriptions, where the two obfuscate their difference from each other as well as the distinction between them and reality in itself.
                </p>
                <div class="mb-6 break-inside-avoid">
                    <img src="/images/delphic-future/covenant-2.jpg" class="max-w-full md:max-h-[calc(100vh_-_300px)] h-auto w-auto" />
                    <p class="text-sm">Amanda Beech, <em>Covenant Transport Move or Die</em>, 2015 installation view at Twelve Ten Gallery.</p>
                </div>
                <p>
                    <strong>EVS</strong> As I see it, the profound development that the ars can claim is that it shows us how logical truths, as explanandums, can be conditioned by their explanans. Propositions make available new forms of conceptual thought, new descriptive concepts, and so when used correctly, bring new empirical properties to the fore. I see all of this as necessary when engaging in the philosophical labor of thinking about possible worlds.
                </p>
                <p>
                    Attempting to structure a possible world can inadvertently, rather than deliberately, produce dysfunctional systems, because we usually can't see how underlying philosophical assumptions erect a specific world restricted to those assumptions. While conceptually, we understand that there is always a gap between the world we describe and "reality", does this imply that were we to refine our technologies of expression, we could then narrow this gap? What does it mean, in this specific use case, that we call these technologies ‘art’? Does art teach us anything about how we grasp the world and what worlds might become?
                </p>
                <p>
                    I think this is also a concept that the artist and theorist Kieth Tilford is working with in his research in AI and beliefs in the human's unique capacity for creativity, where the battleground is really just fought at the level of our unique capacity for rabidly supporting copyright. As I understand it, Tilford uses the rule based system of AI as a vector to savagely detract from a human-exceptionalist concept of creativity, style, and imagination in a similar way to how you're talking about Llull's device. The demonstration that explanations actually only explain, or uncover, their own mechanical nature is explicated by one of Tilford's points: That discourse around imagination, and imagination itself, are practically indissociable. But when it is then recognized that discourse is conditioned by a linguistic and symbolic history, and that such language can break down into logical normative components, well we also break down imagination into these components as well. This "algorithmic decomposition", as it is called, demonstrates that, from a certain perspective, imagination can be understood from a rule-governed position, and so the opportunity for understanding rules is also the opportunity for understanding something like the Kantian imagination. This vents the pressure that something like the romantic notion of "creativity" imposes. Creatively is a highly manipulative concept because once it is critically investigated we see how evasive it is to criticality itself.
                </p>
                <p>
                    <strong>AB</strong> I would like to think optimistically that a technology called art can have the capacity to help us think in a structured, analytical and logical ways about the rift between sayings and doings without over-determining the rift itself as false consciousness or fetishized reification of possibility for possibility’s sake. I think it's very easy to enjoy the elision between complexity and impossibility too much. I also think it's important to understand how the machinations of AI as a non-human form of intelligence are precisely mimicking and continuing the combinatory processes of an idealist post-structural remix culture in which we can confront our semantic pessimism. This means that we are unable to tell the difference between absolute finitude and the capacity for transcendental thought that is actually required to even diagnose this condition. There is a space for us to mine as artists, as thinking makers, in our subjectivity and non-subjectivity. And thus we can work on becoming more aware of the normative conditions that are implicit to and necessary for any hypothetical claims, without saying that they are reducible to each other, or that because norms are necessary then the freedoms that seem to be available by fictions are damaged because they are not unlimited. What if we were to take finitude seriously? What if we say that ends are not on a repeating loop of the same, and we say that difference is not simply a question of different forms and expressions emerging from the same structures, and rather that by understanding the question of reality we will be compelled to follow different rules, principles and structures, all with their own semantically laden conditions. This returns us to questions of revolutionary subjectivity.
                </p>
                <p>
                    <strong>EVS</strong> I think this has a lot to do with the title of the show as well. Delphic Future, is a kind of conceptual doubling of the term "prophecy", which obviously relates to the Ars. However, in regard to art, I was thinking about another form of prophecy: that of eschatology. If we are to say that art needs to be ingrained in a specific set of rule based research practices in order to maintain a status of "art", rather than, for example, accidentally become something like engineering, does this mean the potential of artistic creativity is limited by the potential of the rules that govern it? I suppose what I'm asking is how, whether it is art or the artist, can one be emancipated from a system that is an essential condition in one's own self-recognition? Are we required to engage only with the systems that limit us? If I, as a political subject, am defined by something like the capital relation, how can I come to dismantle (or destroy) capital, which is the project of a critical political form, without inevitably dismantling (or destroying) myself? Is this not eschatological? How can art project its thought towards a future where it knows it can't find itself?
                </p>
                <p>
                    <strong>AB</strong> It really is the question many of us are asking: To what extent do we construct the thing we critique by means of the critique itself? (We make the monster we seek to destroy.) The capital relation is one defining factor of what we are, but it is not the only one, there have been times where different forms of abstracting conditions defined our world and our place in it. We also have to ask what we mean by the capital relation itself? Are we saying that the alienating force of capital is what conditions our thought <em>tout court</em>? There are multiple forms of alienation, as we talked about earlier the process of self-awareness is an alienating process, this is not the exact same process of alienation that capital naturalizes for us and <em>in us</em>. The term "Delphic Future" is taken from the last chapter of Alan Greenspan's autobiography. He uses this term to relate to what became necessary as Chair of the Federal Reserve Bank, which was to speak in public about the future of the financial market. Here he has to use fedspeak, or a delphi dialect which means that he had to ensure that nothing he said could lead to any determinate outcome, and so he had to keep his terms ambiguous so as to not influence the market itself by saying something about it, whilst having to say something about it. This position of crafting an open future has been core to the political claims of art. But here it obviously serves the interests of capital. It is not crafting the openness of all possibilities but of warding against specific imbalances that could occur from the voice of future management. In that sense the question of a delphic future is a subject matter that the works aim to explore as a dynamic problem. I believe there should always be an attempt to think about these multiple vectors of alienation without collapsing them into one; to think of these terms/myths of openness as irreducible and to understand that we need a stringent approach to thinking inside this space of negativity. How we think of the negation at work in a critical analysis constructively is for me to see the artwork as a place of explication by <em>other means</em>. This is not the Brechtian form of explication that reveals the underlying conditions of power, nor is this to act as if the work has managed to render a "stabilized" image of dehesion in a new aesthetics of crisis, but instead I think the artwork has the capacity to extrapolate the dynamic of the non-relational condition of alienation, in and beyond capitalist principles and this in itself holds the question of finitude and the future. This asks for a rationalist realism that determines itself against the perpetuation of self-picturing.
                </p>
            </div>
            <div class="mt-10">
                <p class="italic"><span class="font-bold">Amanda Beech</span> is an artist and writer. Her work entangles narratives of power, cause and contingency from philosophical theory, science, literature and real political events. Here the  material conditions of thought, myth and fiction that seem necessary for an account of human agency are explored as forms of ideological and rhetorical force. In video, painting, print and sculpture her work proposes art as a form of intelligence and power beyond the ideals of capitalism and the limits that art has set for itself by means of its critiques.</p>
                <p class="italic mb-6">She has exhibited widely in various Biennales and has written texts for anthologies and museum catalogs. She has edited and contributed to numerous books including <span class="font-bold">Construction Site for Possible Worlds</span>, 2019, Urbanomic/MIT Press and <span class="font-bold">Cold War, Cold World</span>, Urbanomic, 2015. Her recent writing includes an essay on Jean Francois Lyotard’s exhibition "Les Immateriaux for Beyond Matter", ZKM, Karlsruhe. Forthcoming work includes a new book on art, aesthetics and philosophy; <span class="font-bold">The Intolerable Image</span>, from MIT. </p>
                <p class="italic"><span class="font-bold">Ellis von Sternberg</span> is one half of an artist duo with Parker von Sternberg  (b. 1990 &amp; 1988). They are based between New York, NY and Minneapolis, MN. Previous exhibitions include King’s Leap Fine Arts (New York, NY), Freddy (Harris, NY), and Triest (Brooklyn, NY). Ellis von Sternberg received his BFA from the School of the Art Institute of Chicago. Parker von Sternberg is licensed to practice law in Minnesota and received his degree from the University of Minnesota.</p>
            </div>
        </div>
    </div>
</template>
